--###########################################################################################
-- THIS CODE IS AUTO-GENERATED BY THE generate_LUT.py SCRIPT based on the following values:
-- OSC_INDEX_WIDTH     = {{ index_width }}
-- OSC_AMPLITUDE_WIDTH = {{ amplitude_width }}
--###########################################################################################

library ieee;
use ieee.std_logic_1164.all;
use work.oscillator_pkg.all;

package sin_LUT_pkg is
    constant ROM_DEPTH : integer := 2 ** OSC_INDEX_WIDTH;
    type ROM_type is array(0 to ROM_DEPTH-1) of std_logic_vector(OSC_AMPLITUDE_WIDTH-1 downto 0);
    constant ROM_data : ROM_type := (
    {% for amplitude in amplitudes %}
        "{{ amplitude }}"{{ ", " if not loop.last else "" }}
    {% endfor %}
    );
end package sin_LUT_pkg;